<?php
/* @var $this DevForce */
?>
<style>
.disable{
	color:gray;
}
</style>
<?php print $description; ?>
<?php if(isset($record[0])): ?>
<table id="dev-force-data-table" class="tablesorter border-0" border=1>
	<!-- table header -->
	<thead>
		<tr>
			<td class="border-0">
			</td>
			<?php foreach( $column_struct as $column_name => $struct ): ?>
				<?php
				if(!empty($struct['hidden'])){ continue; }
				$column	 = $struct['field'];
				$type	 = $struct['type'];
				$comment = $struct['comment'];
				$length	 = isset($struct['length']) ? $struct['length']: null;
				$label	 = isset($struct['label']) ? $struct['label']: $column_name;
				?>
				<th class="" type="<?php print $type ?>" lengty="<?php print $length ?>" column="<?php print $column ?>">
					<span title="<?php print $comment ?>">
						<?php print $label ?>
					</span>
				</th>
			<?php endforeach; ?>
		</tr>
	</thead>
	
	<!-- table data -->
	<tbody>
		<?php foreach( $record as $index => $columns ): ?>
			<tr pvar="<?php print $columns[$pkey] ?>">
				<td class="border-0">
					<input type="button" name="" value="delete"  />
				</td>
				<?php foreach( $columns as $column_name => $value ): ?>
					<?php
					if(!empty($column_struct[$column_name]['hidden'])){ continue; }
					$disable = empty($column_struct[$column_name]['disable']) ? null: 'disable';
					?>
					<td class="update" column="<?php print $column_name ?>">
						<div class="value <?php print $disable ?>"><?php print $value ?></div>
					</td>
				<?php endforeach; ?>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php endif; ?>

<script type="text/javascript" src="<?php print $this->ConvertURL('app:/js/jquery-1.11.0.min.js') ?>"></script>
<script type="text/javascript" src="<?php print $this->ConvertURL('app:/js/jquery.tablesorter.min.js') ?>"></script>
<script type="text/javascript" src="<?php print $this->ConvertURL('app:/js/jquery.tablesorter.pager.js') ?>"></script>
<script>
jQuery(function($) {
	//	Add click event (update)
	$(".update").click(function(event){
		//	width
		var width = $(this).width()-6;
		
		//	hide
		$(this).children(".value").hide();
		
		//	input
		if( $(this).children(".input").size() ){
			//	exists
			$(this).children(".input").show().focus();
			return;
		}else{
			//	init input
			var $input = $("<input />");
			$input.addClass("input");
			$input.css('width', width );
			$input.val( $(this).children(".value").html() );
			$(this).append($input);
			$input.focus();
		}
		
		$input.blur(function(event){
			//	init
			var pvar   = $(this).parent().parent().attr('pvar');
			var column = $(this).parent().attr('column');
			var value  = $(this).val();
			var page   = '<?php print $page ?>';
			var dml    = 'update';
			
			//	compare
			if( $(this).val() != $(this).parent().children(".value").html() ){
				
				//	init post data
				var data = {page: page, dml: dml, id: pvar, column: column, value: value};
				
				//	ajax
				$.ajax({
					type: "GET",
					url: "<?php print $this->ConvertURL('app:/ajax') ?>", 
					context: $(this), 
					data: data,
					success: function(result){
						var json = $.parseJSON(result);
						//	LOGOUT
						if(json.status == 'LOGOUT'){
							location.reload();
						}	
						//	ERROR
						if(json.error){
							alert(json.error);
							return;
						}
						//	OK
						var value = json.value;
						$(this).parent().children(".value").html(value);
						$(this).val(value);
					}
				});
			}
			
			$(this).hide();
			$(this).parent().children(".value").show();
		});
	});
});
</script>
