<?php
/* @var $this DevForce */
//$this->mark();
//$this->d($record[0]);
//$this->d($config);
//$this->d($column_struct);
?>
<style>
.disable{
	color:gray;
}
</style>
<?php print $description; ?>
<?php if(isset($record[0])): ?>
<table id="myTable" class="tablesorter" border=1>
	<!-- table header -->
	<thead>
		<tr>
			<?php foreach( $column_struct as $struct ): ?>
				<?php
				if(!empty($struct['hidden'])){ continue; }
				$column	 = $struct['field'];
				$type	 = $struct['type'];
				$comment = $struct['comment'];
				$length	 = isset($struct['length']) ? $struct['length']: null;
				$label	 = isset($struct['label']) ? $struct['label']: $column;
				?>
				<th class="" type="<?php print $type ?>" lengty="<?php print $length ?>" column="<?php print $column ?>">
					<span title="<?php print $comment ?>">
						<?php print $label ?>
					</span>
				</th>
			<?php endforeach; ?>
		</tr>
	</thead>
	
	<!-- table data -->
	<tbody>
		<?php foreach( $record as $index => $columns ): ?>
			<tr pvar="<?php print $columns[$pkey] ?>">
				<?php foreach( $columns as $column_name => $value ): ?>
					<?php
					if(!empty($column_struct[$column_name]['hidden'])){ continue; }
					$disable = empty($column_struct[$column_name]['disable']) ? null: 'disable';
					?>
					<td class="edit" column="<?php print $column_name ?>">
						<span class="value <?php print $disable ?>"><?php print $value ?></span>
					</td>
				<?php endforeach; ?>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<!--
<div id="pager1">
	<a class="first">&lt;&lt;</a>
	<a class="prev">&lt;</a>
	<input class="pagedisplay" type="text">
	<a class="next">&gt;</a>
	<a class="last">&gt;&gt;</a>
	<select class="pagesize">
		<option>25</option>
		<option selected="selected">50</option>
		<option>100</option>
		<option>1000</option>
	</select>
</div> 
 -->

<div id="pager2">
	<a class="first">&lt;&lt;</a>
	<a class="prev">&lt;</a>
	<span class="pagehint"></span>
	<a class="next">&gt;</a>
	<a class="last">&gt;&gt;</a>
	<select class="pagesize">
		<option>10</option>
		<option>20</option>
		<option>25</option>
		<option>50</option>
		<option>100</option>
	</select>
</div>

<?php endif; ?>

<script type="text/javascript" src="<?php print $this->ConvertURL('app:/js/jquery-1.11.0.min.js') ?>"></script>
<script type="text/javascript" src="<?php print $this->ConvertURL('app:/js/jquery.tablesorter.min.js') ?>"></script>
<script type="text/javascript" src="<?php print $this->ConvertURL('app:/js/jquery.tablesorter.pager.js') ?>"></script>
<script>
jQuery(function($) {
	/*
	//	Setup table sorter
	var init_sort_column = 4;
	var init_sort_order  = 1;
	$("#myTable").tablesorter({
	//	sortList: [[init_sort_column,init_sort_order]]
		widthFixed: true,
		widgets: ['zebra']
	}).tablesorterPager({
		container: $('#pager'),
		size: 50,
		positionFixed: false
	});
	*/
	
	//	Add click event
	$(".edit").click(function(event){
		//	hide
		$(this).children(".value").hide();

		//	input
		if( $(this).children(".input").size() ){
			//	exists
			$(this).children(".input").show().focus();
			return;
		}else{
			//	init input
			var $input = $("<input />");
			$input.addClass("input");
			$input.val( $(this).children(".value").html() );
			$(this).append($input);
			$input.focus();
		}
		
		$input.blur(function(event){
			//	init
			var pvar   = $(this).parent().parent().attr('pvar');
			var column = $(this).parent().attr('column');
			var value  = $(this).val();
			var page   = '<?php print $page ?>';
			
			//	compare
			if( $(this).val() != $(this).parent().children(".value").html() ){
				
				//	init post data
				var data = {page: page, id: pvar, column: column, value: value};
				
				//	ajax
				$.ajax({
					type: "GET",
					url: "<?php print $this->ConvertURL('app:/ajax') ?>", 
					context: $(this), 
					data: data,
					success: function(result){
						json = $.parseJSON(result);
						//	LOGOUT
						if(json.status == 'LOGOUT'){
							location.reload();
						}	
						//	ERROR
						if(json.error){
							alert(json.error);
							return;
						}
						//	OK
						$(this).parent().children(".value").html(json.value);
						$(this).val(json.value);
					}
				});
			}
			
		//	$(this).remove();
			$(this).hide();
			$(this).parent().children(".value").show();
		});
	});
});

jQuery(function($){
	function pageHint(sorter){
		$(sorter).each(function(){
			var c = this.config;
			var total = c.totalRows;
			var from = c.page * c.size + 1;
			var to = (c.page + 1) * c.size;
			if (to > total)
			to = total;
			$(c.cssPageHint, c.container).text([total, '件中', from, '-', to, '件目'].join(' '));
		});
	}
	
	var pager = $('#pager2');
	var sorter = $('#myTable')
		.tablesorter({
			widgets: ['zebra']
		})
		.tablesorterPager({
			container: pager,
			size: 10,
			cssPageHint: '.pagehint',
			positionFixed: false
		}); 

	$('.next, .prev, .first, .last', pager)
		.click(function() {
			pageHint(sorter);
		});

	$('.pagesize', pager)
		.change(function() {
			pageHint(sorter);
		});
	
	pageHint(sorter);
}); //jQuery
</script>
