<head>
	<meta charset="<?=$this->GetCharset()?>">
	
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="Content-Style-Type" content="text/css">
	
	<meta name="keywords" content="<?=$this->GetKeywords()?>">
	<meta name="description" content="<?=$this->GetDescription()?>">
	
	<link rel="stylesheet" type="text/css" href="<?php print $this->ConvertURL('app:/css/import.css') ?>">
	
    <link rel="shortcut icon" href="<?=$this->ConvertURL('app:/favicon.ico')?>" type="image/vnd.microsoft.icon" />
    <link rel="icon" href="<?=$this->ConvertURL('app:/favicon.ico')?>" type="image/vnd.microsoft.icon" />
	
	<title><?=$this->GetTitle()?></title>
</head>
